apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pulsarclusters.pulsar.apache.org
spec:
  group: pulsar.apache.org
  names:
    kind: PulsarCluster
    listKind: PulsarClusterList
    plural: pulsarclusters
    singular: pulsarcluster
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            bookie:
              description: Bookie defines the desired state of Bookie
              properties:
                image:
                  description: Image is the  container image. default is apachepulsar/pulsar-all:latest
                  properties:
                    pullPolicy:
                      type: string
                    repository:
                      type: string
                    tag:
                      type: string
                  required:
                  - repository
                  - tag
                  - pullPolicy
                  type: object
                labels:
                  additionalProperties:
                    type: string
                  description: Labels specifies the labels to attach to pods the operator
                    creates for the bookie cluster.
                  type: object
                pod:
                  description: Pod defines the policy to create pod for the bookie
                    cluster.  Updating the Pod does not take effect on any existing
                    pods.
                  properties:
                    affinity:
                      description: The scheduling constraints on pods.
                      type: object
                    annotations:
                      additionalProperties:
                        type: string
                      description: Annotations specifies the annotations to attach
                        to pods the operator creates.
                      type: object
                    env:
                      description: List of environment variables to set in the container.
                        This field cannot be updated.
                      items:
                        type: object
                      type: array
                    labels:
                      additionalProperties:
                        type: string
                      description: Labels specifies the labels to attach to pods the
                        operator creates for the pulsar cluster.
                      type: object
                    nodeSelector:
                      additionalProperties:
                        type: string
                      description: NodeSelector specifies a map of key-value pairs.
                        For the pod to be eligible to run on a node, the node must
                        have each of the indicated key-value pairs as labels.
                      type: object
                    resources:
                      description: Resources is the resource requirements for the
                        container. This field cannot be updated once the cluster is
                        created.
                      type: object
                    securityContext:
                      description: 'SecurityContext specifies the security context
                        for the entire pod More info: https://kubernetes.io/docs/tasks/configure-pod-container/security-context'
                      type: object
                    terminationGracePeriodSeconds:
                      description: TerminationGracePeriodSeconds is the amount of
                        time that kubernetes will give for a pod instance to shutdown
                        normally. The default value is 1800.
                      format: int64
                      type: integer
                    tolerations:
                      description: Tolerations specifies the pod's tolerations.
                      items:
                        type: object
                      type: array
                  required:
                  - terminationGracePeriodSeconds
                  type: object
                size:
                  description: Size (DEPRECATED) is the expected size of the bookie
                    cluster. This has been replaced with "Replicas"  The valid range
                    of size is from 1 to 7.
                  format: int32
                  type: integer
              required:
              - image
              - size
              type: object
            broker:
              description: Broker defines the desired state of Broker
              properties:
                image:
                  description: Image is the  container image. default is apachepulsar/pulsar-all:latest
                  properties:
                    pullPolicy:
                      type: string
                    repository:
                      type: string
                    tag:
                      type: string
                  required:
                  - repository
                  - tag
                  - pullPolicy
                  type: object
                labels:
                  additionalProperties:
                    type: string
                  description: Labels specifies the labels to attach to pods the operator
                    creates for the broker cluster.
                  type: object
                pod:
                  description: Pod defines the policy to create pod for the broker
                    cluster.  Updating the Pod does not take effect on any existing
                    pods.
                  properties:
                    affinity:
                      description: The scheduling constraints on pods.
                      type: object
                    annotations:
                      additionalProperties:
                        type: string
                      description: Annotations specifies the annotations to attach
                        to pods the operator creates.
                      type: object
                    env:
                      description: List of environment variables to set in the container.
                        This field cannot be updated.
                      items:
                        type: object
                      type: array
                    labels:
                      additionalProperties:
                        type: string
                      description: Labels specifies the labels to attach to pods the
                        operator creates for the pulsar cluster.
                      type: object
                    nodeSelector:
                      additionalProperties:
                        type: string
                      description: NodeSelector specifies a map of key-value pairs.
                        For the pod to be eligible to run on a node, the node must
                        have each of the indicated key-value pairs as labels.
                      type: object
                    resources:
                      description: Resources is the resource requirements for the
                        container. This field cannot be updated once the cluster is
                        created.
                      type: object
                    securityContext:
                      description: 'SecurityContext specifies the security context
                        for the entire pod More info: https://kubernetes.io/docs/tasks/configure-pod-container/security-context'
                      type: object
                    terminationGracePeriodSeconds:
                      description: TerminationGracePeriodSeconds is the amount of
                        time that kubernetes will give for a pod instance to shutdown
                        normally. The default value is 1800.
                      format: int64
                      type: integer
                    tolerations:
                      description: Tolerations specifies the pod's tolerations.
                      items:
                        type: object
                      type: array
                  required:
                  - terminationGracePeriodSeconds
                  type: object
                size:
                  description: Size (DEPRECATED) is the expected size of the broker
                    cluster. This has been replaced with "Replicas"  The valid range
                    of size is from 1 to 7.
                  format: int32
                  type: integer
              required:
              - image
              - size
              type: object
            zookeeper:
              description: Zookeeper defines the desired state of Zookeeper
              properties:
                image:
                  description: Image is the  container image. default is apachepulsar/pulsar-all:latest
                  properties:
                    pullPolicy:
                      type: string
                    repository:
                      type: string
                    tag:
                      type: string
                  required:
                  - repository
                  - tag
                  - pullPolicy
                  type: object
                labels:
                  additionalProperties:
                    type: string
                  description: Labels specifies the labels to attach to pods the operator
                    creates for the zookeeper cluster.
                  type: object
                pod:
                  description: Pod defines the policy to create pod for the zookeeper
                    cluster.  Updating the Pod does not take effect on any existing
                    pods.
                  properties:
                    affinity:
                      description: The scheduling constraints on pods.
                      type: object
                    annotations:
                      additionalProperties:
                        type: string
                      description: Annotations specifies the annotations to attach
                        to pods the operator creates.
                      type: object
                    env:
                      description: List of environment variables to set in the container.
                        This field cannot be updated.
                      items:
                        type: object
                      type: array
                    labels:
                      additionalProperties:
                        type: string
                      description: Labels specifies the labels to attach to pods the
                        operator creates for the pulsar cluster.
                      type: object
                    nodeSelector:
                      additionalProperties:
                        type: string
                      description: NodeSelector specifies a map of key-value pairs.
                        For the pod to be eligible to run on a node, the node must
                        have each of the indicated key-value pairs as labels.
                      type: object
                    resources:
                      description: Resources is the resource requirements for the
                        container. This field cannot be updated once the cluster is
                        created.
                      type: object
                    securityContext:
                      description: 'SecurityContext specifies the security context
                        for the entire pod More info: https://kubernetes.io/docs/tasks/configure-pod-container/security-context'
                      type: object
                    terminationGracePeriodSeconds:
                      description: TerminationGracePeriodSeconds is the amount of
                        time that kubernetes will give for a pod instance to shutdown
                        normally. The default value is 1800.
                      format: int64
                      type: integer
                    tolerations:
                      description: Tolerations specifies the pod's tolerations.
                      items:
                        type: object
                      type: array
                  required:
                  - terminationGracePeriodSeconds
                  type: object
                size:
                  description: Size (DEPRECATED) is the expected size of the zookeeper
                    cluster. This has been replaced with "Replicas"  The valid range
                    of size is from 1 to 7.
                  format: int32
                  type: integer
              required:
              - image
              - size
              type: object
          type: object
        status:
          properties:
            phase:
              description: Pulsar Cluster Phase
              type: string
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
