apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulsar-operator
  namespace: default

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pulsar-operator
  namespace: default
rules:
- apiGroups:
  - pulsar.apache.org
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pulsar-operator-role-binding
subjects:
- kind: ServiceAccount
  name: pulsar-operator
  namespace: default
roleRef:
  kind: Role
  name: pulsar-operator
  apiGroup: rbac.authorization.k8s.io